
import { ServiceData } from '@/types/service';

// Mock services for testing
export const mockServices: ServiceData[] = [
  {
    id: 'service-1',
    title: 'Math Tutoring for Highschool Students',
    description: 'Expert tutoring in algebra, calculus, and geometry for high school students.',
    type: 'tutoring',
    price: 35,
    rating: 4.8,
    location: 'Online',
    image: 'https://images.unsplash.com/photo-1543599538-a6c4f6cc5c05?w=500&auto=format&fit=crop',
    provider_id: 'user-2',
    provider_name: 'Jane Smith',
    provider_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop',
    subjects: ['Math', 'Calculus', 'Algebra'],
    availability: ['Weekdays', 'Evenings'],
    provider: 'Jane Smith',
    providerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop',
    providerRating: 4.8,
    providerReviews: 24,
    priceUnit: 'hour',
    locations: ['Online'],
    serviceType: 'tutoring',
    grade: 'High School',
    featured: true
  },
  {
    id: 'service-2',
    title: 'English Literature Tutoring',
    description: 'Comprehensive guidance for English literature students of all levels.',
    type: 'tutoring',
    price: 30,
    rating: 4.6,
    location: 'In-person',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f0?w=500&auto=format&fit=crop',
    provider_id: 'user-4',
    provider_name: 'Robert Johnson',
    provider_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop',
    subjects: ['English', 'Literature', 'Writing'],
    availability: ['Weekends', 'Afternoons'],
    provider: 'Robert Johnson',
    providerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop',
    providerRating: 4.6,
    providerReviews: 18,
    priceUnit: 'hour',
    locations: ['In-person', 'New York City'],
    serviceType: 'tutoring',
    grade: 'College',
    featured: false
  },
  {
    id: 'service-3',
    title: 'After-school Childcare',
    description: 'Safe and engaging childcare for school-aged children.',
    type: 'childcare',
    price: 25,
    rating: 4.9,
    location: 'In-person',
    image: 'https://images.unsplash.com/photo-1526634332515-d56c5fd16991?w=500&auto=format&fit=crop',
    provider_id: 'user-3',
    provider_name: 'Sarah Miller',
    provider_avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&auto=format&fit=crop',
    subjects: ['Childcare', 'Homework Help'],
    availability: ['Weekdays', 'Afternoons'],
    provider: 'Sarah Miller',
    providerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&auto=format&fit=crop',
    providerRating: 4.9,
    providerReviews: 32,
    priceUnit: 'hour',
    locations: ['In-person', 'Boston'],
    serviceType: 'childcare',
    grade: 'Elementary',
    featured: true
  }
];
