// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqdlysbqwotdyuuigpvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZGx5c2Jxd290ZHl1dWlncHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NTU2NzEsImV4cCI6MjA1NzQzMTY3MX0.dIGPNU15vuQTfm3IiDleQOfV-200a2_QnpdCRwNcICs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);